name: Deploy Supabase

on:
  push:
    branches: [main]
    paths:
      - 'backend/supabase/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      APPLE_BUNDLE_ID: ${{ vars.APPLE_BUNDLE_ID }}
      APPLE_TEAM_ID: ${{ vars.APPLE_TEAM_ID }}
      APNS_KEY_ID: ${{ secrets.APNS_KEY_ID }}
      APNS_P8_CERTIFICATE: ${{ secrets.APNS_P8_CERTIFICATE }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Apple Bundle ID
        run: |
          supabase secrets set APPLE_BUNDLE_ID="$APPLE_BUNDLE_ID" --project-ref $SUPABASE_PROJECT_ID

      - name: Set Apple Team ID
        run: |
          supabase secrets set APPLE_TEAM_ID="$APPLE_TEAM_ID" --project-ref $SUPABASE_PROJECT_ID

      - name: Set APNS Key ID
        run: |
          supabase secrets set APNS_KEY_ID="$APNS_KEY_ID" --project-ref $SUPABASE_PROJECT_ID

      - name: Set APNS P8 Certificate
        run: |
          supabase secrets set APNS_P8_CERTIFICATE="$APNS_P8_CERTIFICATE" --project-ref $SUPABASE_PROJECT_ID

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Login to Supabase
        run: supabase login --token $SUPABASE_ACCESS_TOKEN
      
      - name: Link to Supabase project
        working-directory: ./backend/supabase
        run: supabase link --project-ref $SUPABASE_PROJECT_ID --password "$SUPABASE_DB_PASSWORD"
      
      - name: Deploy database migrations
        working-directory: ./backend/supabase
        run: supabase db push
      
      - name: Deploy Edge Functions
        working-directory: ./backend/supabase
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID

      - name: Verify deployment
        working-directory: ./backend/supabase
        run: |
          echo "✅ Supabase deployment completed"
          echo "Database migrations applied"
          echo "Edge functions deployed"
